version: '2'

services:
  proxy:
    image: sourcelair/ceryx-proxy:latest
  api:
    image: sourcelair/ceryx-api:latest
  manager:
    image: sourcelair/ceryx-manager:latest
  redis:
    image: redis:3.2.3-alpine
  postgres:
    image: postgres:9.6.2-alpine
