version: '2'

services:
  proxy:
    extends:
      file: base.yaml
      service: proxy
    build: ./proxy
    ports:
      - 80
    environment:
      - CERYX_REDIS_HOST=redis
      - CERYX_REDIS_PORT=6379
    volumes:
      - ./proxy/nginx/conf:/usr/local/openresty/nginx/conf
      - ./proxy/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./proxy/nginx/sites-enabled:/usr/local/openresty/nginx/sites-enabled

  api:
    extends:
      file: base.yaml
      service: api
    build: ./api
    command: python /opt/ceryx/bin/ceryx-api-server.py
    ports:
      - 5555
    environment:
      - CERYX_REDIS_HOST=redis
      - CERYX_REDIS_PORT=6379
      - CERYX_API_HOST=0.0.0.0
    volumes:
      - ./api:/opt/ceryx
  
  manager:
    build: ./manager
    command: python /opt/ceryx/bin/ceryx-manager-server.py
    ports:
      - '8080:8080'
    environment:
      - CERYX_API_HOST=api
      - CERYX_API_PORT=5555
      - CERYX_WEB_HOST=0.0.0.0
      - CERYX_SECRET_KEY=/var/run/secret-key.txt
    volumes:
      - './manager:/opt/ceryx'
      - './sample-secret-key.txt:/var/run/secret-key.txt'
      - '/var/run/docker.sock:/var/run/docker.sock'

  redis:
    extends:
      file: base.yaml
      service: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
