version: '3.1'

services:
  proxy:
    image: sourcelair/ceryx-proxy:latest
    build: ./proxy
    depends_on:
      - redis
    ports:
      - "8000:80"
    networks:
      - default
      - proxy
    environment:
      - CERYX_REDIS_HOST=redis
      - CERYX_REDIS_PORT=6379
      - CERYX_CACHE_EXPTIME=300
    volumes:
      - ./proxy/nginx/conf:/usr/local/openresty/nginx/conf
      - ./proxy/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./proxy/nginx/sites-enabled:/usr/local/openresty/nginx/sites-enabled
  
  manager:
    image: sourcelair/ceryx-manager:latest
    build: ./manager
    command: python /opt/ceryx/bin/ceryx-manager-server.py
    depends_on:
      - redis
    deploy:
      placement:
        constraints:
          - node.role==manager
    ports:
      - '8080:8080'
    environment:
      - CERYX_WEB_HOST=0.0.0.0
      - CERYX_SECRET_KEY=/run/secrets/secret-key.txt
      - CERYX_PROXY_NETWORK=proxy
      - CERYX_REDIS_HOST=redis
      - CERYX_REDIS_PORT=6379
    volumes:
      - './manager:/opt/ceryx'
      - '/var/run/docker.sock:/var/run/docker.sock'
    secrets:
      - source: manager_secret_key
        target: secret-key.txt

  redis:
    image: redis:3.2.3-alpine
    volumes:
      - redis_data:/data
  
  redis-commander:
    image: redis-commander
    build: redis-commander
    command: --redis-host redis
    ports:
      - '8081:8081'

volumes:
  redis_data:

networks:
  proxy:
    external: true

secrets:
  manager_secret_key:
    file: ./sample-secret-key.txt
